---
title: "Housing Data"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(reshape2)
library(lubridate)
```

```{r}
rates <- read.csv('mortgage_rate.csv', header=TRUE)

#convert DATE column to date format
rates$DATE <- as.Date(rates$DATE, format = "%m/%d/%y")

#add year and month columns to later merge with other data
rates$year <- year(rates$DATE)
rates$month <- month(rates$DATE, label=TRUE)

#keep only the first instance of rate data for each month
rates_1st <- aggregate(MORTGAGE30US ~ month + year, rates, FUN = function(x) x[1])

head(rates_1st)
```
```{r}
cpi <- read.csv('cpi.csv', header=TRUE)

#reshape monthly columns to one column
cpi_transform <- melt(cpi, id.vars = "Year", variable.name = "month", value.name = "cpi") %>% rename(year = Year)

head(cpi_transform)
```

```{r}
listings <- read.csv('active_listing.csv', header=TRUE)

#convert DATE column to date format
listings$observation_date <- as.Date(listings$observation_date, format = "%Y-%m-%d")

#add year and month columns to later merge with other data
listings$year <- year(listings$observation_date)
listings$month <- month(listings$observation_date, label=TRUE)

head(listings)
```

```{r}
value_index <- read.csv('zillow_home_value_index.csv', header=TRUE)
head(value_index)

#reshape date columns and convert to datetime format
price <- value_index %>%
  pivot_longer(cols = starts_with("X"),
               names_to = "date",
               values_to = "value") %>%
  mutate(date = gsub("X", "", date),
         date = as.Date(date, format = "%m.%d.%y")) %>%
  mutate(date = floor_date(date, unit = "month"))

#rename columns for merge with final dataset
price <- price %>% rename(ST = State, CTYNAME = RegionName, STATE = StateCodeFIPS, COUNTY = MunicipalCodeFIPS)

price
```

```{r}
pop_2010_2020 <- read.csv('population_2010_2020.csv', header=TRUE)
pop_2020_2022 <- read.csv('population_2020_2022.csv', header=TRUE)

#combine both datasets into one
pop_2010_2022 <- merge(pop_2010_2020, pop_2020_2022, by = c("STATE", "COUNTY", "STNAME", "CTYNAME"))
pop_10_22 <- pop_2010_2022[, c("STATE", "COUNTY", "STNAME", "CTYNAME", "POPESTIMATE2010", "POPESTIMATE2011", "POPESTIMATE2012", "POPESTIMATE2013", "POPESTIMATE2014", "POPESTIMATE2015", "POPESTIMATE2016", "POPESTIMATE2017", "POPESTIMATE2018", "POPESTIMATE2019", "POPESTIMATE2020.y", "POPESTIMATE2021", "POPESTIMATE2022")]

#filter by counties with a significant population (greater than 2,000,000)
sig_pop <- pop_10_22 %>% filter(COUNTY != 0, POPESTIMATE2022 > 2000000)
sig_pop
#reshape population dataset and convert column names to years
pop <- sig_pop %>%
  pivot_longer(cols = starts_with("POPESTIMATE"),
               names_to = "year",
               values_to = "pop") %>%
  mutate(year = gsub("POPESTIMATE", "", year)) %>%
  mutate(year = gsub(".y", "", year)) %>%
  mutate(year = as.numeric(year))

#top 16 counties with population data
pop

county_list <- sig_pop[order(sig_pop$STATE), 1:4]
row.names(county_list) <- NULL

#add record ID and reorder columns
county_list <- county_list %>%
  mutate(ID = row_number()) %>%
  select(ID, STATE, COUNTY, STNAME, CTYNAME)

#list of counties with >2,000,000 population
county_list
```

```{r}
#create months dataframe for merging
months_seq <- seq(from = as.Date("2010-01-01"), to = as.Date("2023-05-01"), by = "1 month")
years <- year(months_seq)
months <- month(months_seq, label=TRUE)

T1 <- data.frame(date = months_seq, year = years, month = months)

#merge mortgage rate data
T1_mortgage <- merge(T1, rates_1st, by = c("year", "month"), all.x=TRUE) %>% arrange(date)

#merge cpi data
T1_mortgage_cpi <- merge(T1_mortgage, cpi_transform, by = c("year", "month"), all.x=TRUE) %>% arrange(date)

#merge active listings data
T1_mortgage_cpi_listings <- merge(T1_mortgage_cpi, listings, by = c("year", "month"), all.x=TRUE) %>% arrange(date)

```

```{r}
#plot mortgage rates
plot(T1_mortgage$date, T1_mortgage$MORTGAGE30US, type="l", xlab="Date", ylab="Rate", main="mortgage_rate")
```

```{r}
#plot cpi
plot(T1_mortgage_cpi$date, T1_mortgage_cpi$cpi, type="l", xlab="Date", ylab="CPI", main="CPI")
```

```{r}
#plot active listings
plot(T1_mortgage_cpi_listings$date, T1_mortgage_cpi_listings$ACTLISCOUUS, type="l", xlab="Date", ylab="Active Listings", main="Active Listings")
```

```{r}
#combine mortgage rates, cpi, active listings and counties
combined_data <- merge(T1_mortgage_cpi_listings, county_list, by=NULL)
combined_data

#add population data
combined_data_pop <- merge(combined_data, pop, by = c("year", "STATE", "COUNTY", "STNAME", "CTYNAME"), all.x=TRUE)
combined_data_pop

#combine previous dataset with Zillow home values by county
final <- combined_data_pop %>%
  left_join(price, by = c("date", "CTYNAME", "STATE", "COUNTY"))

#select relevant fields
final <- final %>% select(ID, STATE, COUNTY, STNAME, CTYNAME, date, year, month, MORTGAGE30US, cpi, ACTLISCOUUS, pop, value)

final_sorted <- final %>%
  arrange(ID, date)

final_sorted
summary(final_sorted)
```

